### ISSUE TITLE
Void estabilizer sprite

### ISSUE THREAD

**Issue by feu-follet** [Pietro303HD/ShadowMod#14]
Void estabilizer sprite is mine ! I'm senri on discord and you stole my sprite
Please change it back

**Comment by Pietro303HD** [comment]
wut

**Comment by feu-follet** [comment]
![Screenshot_2020-06-04-23-02-19-819](https://user-images.githubusercontent.com/61912511/83818794-8566d380-a6c8-11ea-8f0e-66eaf3ee6f08.jpeg)

**Comment by feu-follet** [comment]
This
It's the sprite you're using
I made it

**Comment by Pietro303HD** [comment]
Looool, i guess Niirk is too lazy to just make some original sprite

**Comment by feu-follet** [comment]
So tell him to change back the sprite !

**Comment by feu-follet** [comment]
Thank you

**Comment by rodrigolitzius** [comment]
Whafuk is happening
