### ISSUE TITLE
S.E.M.S not right size

### ISSUE THREAD

**Issue by Cyberman-42** [Pietro303HD/ShadowMod#28]
The sprite of S.E.M.S. is I believe 5 tiles wide, while the tile is only three.
This is in the latest release.

**Comment by kapzduke** [comment]
it's 4x4

**Comment by kapzduke** [comment]
and everything is alright with the sprite

**Comment by kapzduke** [comment]
(tho it needs respriting)

**Comment by kapzduke** [comment]
wait i thought you talked about semmg

**Comment by Cyberman-42** [comment]
Ah sorry, I was using the latest release instead of loading it directly from github. My bad

**Comment by Cyberman-42** [comment]
And it was about the size of the block itself

**Comment by Cyberman-42** [comment]
The block of Sems has size 3 while the sprite has size 4

**Comment by rodrigolitzius** [comment]
Lemme check this

**Comment by rodrigolitzius** [comment]
the sprite is really weird, or it is normal, idk

**Comment by rodrigolitzius** [comment]
Its normal
