### ISSUE TITLE
shadow mod clashing mindustry

### ISSUE THREAD

**Issue by lokyinng** [Pietro303HD/ShadowMod#36]

**Comment by lokyinng** [comment]
why the shadow clashing mindustry???

**Comment by rodrigolitzius** [comment]
you mean cRashing? if yes i can't help you without details
@lokyinng

**Comment by lokyinng** [comment]
ok if the stadium or any of the shadow mod stuff used it crashed

**Comment by lokyinng** [comment]
the game

**Comment by rodrigolitzius** [comment]
give me more details and i can help you.

**Comment by rodrigolitzius** [comment]
@lokyinng

**Comment by rodrigolitzius** [comment]
you didn't answer, so I'll have to close.
